# Generated by Django 5.1.4 on 2026-05-22 03:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('identity', '0002_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('payment_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('online', 'Online (Tithely/Stripe)'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_cents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'payment_application',
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligation_type', models.CharField(choices=[('event', 'Event'), ('dues', 'Recurring Dues')], default='event', max_length=10)),
                ('amount_cents', models.PositiveIntegerField()),
                ('paid_cents', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('waived', 'Waived'), ('written_off', 'Written Off'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=15)),
                ('waiver_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='membership.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'obligation',
                'ordering': ['due_date'],
            },
        ),
    ]
