# Generated by Django 5.1.4 on 2026-05-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_initial'),
        ('ledger', '0001_initial'),
        ('membership', '0001_initial'),
        ('obligations', '0001_initial'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='imported_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='reconciliation.importedtransaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ledger_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='membership.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='obligations.obligation'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='obligations.payment'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['organization', 'status'], name='obligation_organiz_cf8f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['member', 'status'], name='obligation_member__780a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['due_date'], name='obligation_due_dat_eab696_idx'),
        ),
    ]
