# Generated by Django 5.1.4 on 2026-05-22 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('bereavement', 'Bereavement'), ('medical_emergency', 'Medical Emergency'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('payout_amount_cents', models.PositiveIntegerField(help_text='Total payout to the affected household, in cents.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('obligations_generated', 'Obligations Generated'), ('collecting', 'Collecting'), ('closed', 'Closed'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=25)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('contribution_deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_override',
            },
        ),
    ]
