# Generated by Django 5.1.4 on 2026-05-22 03:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contribution_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('exempt', 'Exempt')], default='full', max_length=10)),
                ('fraction', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fixed_cap_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'contribution_rule',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for this household.', max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name_am', models.CharField(blank=True, max_length=100)),
                ('last_name_am', models.CharField(blank=True, max_length=100)),
                ('name_aliases', models.TextField(blank=True, help_text='Comma-separated alternate spellings for reconciliation matching.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('deceased', 'Deceased'), ('left', 'Left')], db_index=True, default='active', max_length=15)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('senior', 'Senior'), ('family', 'Family')], default='standard', max_length=15)),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_whatsapp', models.CharField(blank=True, max_length=30)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic')], default='en', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Short code member includes in payment memo for auto-matching.', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('contribution_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='membership.contributionrule')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='membership.household')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembershipHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_history', to='membership.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_history', to='membership.member')),
            ],
            options={
                'db_table': 'household_membership_history',
                'ordering': ['-joined_on'],
            },
        ),
        migrations.AddField(
            model_name='household',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_for', to='membership.member'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['organization', 'status'], name='member_organiz_9d4cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='member_last_na_5d389c_idx'),
        ),
    ]
