# Generated by Django 5.1.4 on 2026-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_familymember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
