# Generated by Django 5.1.4 on 2026-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0002_orgsettings_penalty_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="settingsauditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
