# Generated by Django 5.1.4 on 2026-05-22 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_initial'),
        ('membership', '0001_initial'),
        ('obligations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('bank_csv', 'Bank CSV'), ('tithely_csv', 'Tithely CSV'), ('manual', 'Manual Entry')], max_length=20)),
                ('file', models.FileField(upload_to='reconciliation/imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('payer_name', models.CharField(blank=True, max_length=300)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Auto-Matched'), ('manually_matched', 'Manually Matched'), ('applied', 'Applied to Ledger'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected / Skipped')], default='unmatched', max_length=20)),
                ('confidence_score', models.SmallIntegerField(default=0, help_text='0–100')),
                ('match_explanation', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reconciliation.importbatch')),
                ('matched_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_matches', to='membership.member')),
                ('matched_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_matches', to='obligations.obligation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imported_transaction',
                'indexes': [models.Index(fields=['organization', 'match_status'], name='imported_tr_organiz_05a15d_idx'), models.Index(fields=['transaction_date'], name='imported_tr_transac_43f639_idx'), models.Index(fields=['fingerprint'], name='imported_tr_fingerp_9216df_idx')],
            },
        ),
    ]
