# Generated by Django 5.1.4 on 2026-05-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('identity', '0002_initial'),
        ('membership', '0001_initial'),
        ('obligations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obligations.obligation'),
        ),
        migrations.AddField(
            model_name='communication',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='communication',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obligations.payment'),
        ),
        migrations.AddField(
            model_name='communication',
            name='recipient_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='membership.member'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='communication',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.messagetemplate'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status', 'channel'], name='communicati_status_7dedf8_idx'),
        ),
    ]
